import type { Metadata } from "next";
import { Inter, Open_Sans, Roboto } from "next/font/google";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { BackgroundGradientAnimation } from "@/components/ui/background-gradient-animation";

// const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({
  subsets: ["latin"],
});
export const vazir = Vazirmatn({ subsets: ["arabic"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className}`}>
        <BackgroundGradientAnimation>
        </BackgroundGradientAnimation>
          {children}
      </body>
    </html>
  );
}
